name = "tln-motors"
license = "MIT"
licenselink = "https://github.com/Ravelin/tln-motors-theme/blob/master/LICENSE"
description = "TLN MOTORS THEME"
homepage = "https://github.com/Ravelin/tln-motors-theme"
tags = ["Hugo", "Tailwind CSS", "theme"]
features = []
min_version = "0.1.0"

[author]
  name = "David Murray"
  homepage = "https://github.com/Ravelin/"