name = "tln-motors"
license = "MIT"
licenselink = "https://github.com/Ravelin/tln-motors-theme/blob/master/LICENSE"
description = "TLN MOTORS THEME"
homepage = "https://github.com/Ravelin/tln-motors-theme"
tags = ["Hugo", "Tailwind CSS", "theme"]
features = []
min_version = "0.1.0"

[author]
  name = "David Murray"
  homepage = "https://github.com/Ravelin/"

# build
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'