name = "tln-motors"
license = "MIT"
licenselink = "https://github.com/Ravelin/tln-motors-theme/blob/master/LICENSE"
description = "TLN MOTORS THEME"
homepage = "https://github.com/Ravelin/tln-motors-theme"
tags = ["Hugo", "Tailwind CSS", "theme"]
features = []
min_version = "0.1.0"

[author]
  name = "David Murray"
  homepage = "https://github.com/Ravelin/"

# build
[build]
  useResourceCacheWhen = 'fallback'
  writeStats = true
  [build.buildStats]
    enable = false
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"